const SINGLE_PRODUCT_LOADING = "SINGLE_PRODUCT_LOADING";
const SINGLE_PRODUCT_ERROR = "SINGLE_PRODUCT_ERROR";
const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";

export {SINGLE_PRODUCT_SUCCESS,SINGLE_PRODUCT_ERROR,SINGLE_PRODUCT_LOADING}
