const SEARCH_PRODUCT_LOADING = "SEARCH_PRODUCT_LOADING"
const SEARCH_PRODUCT_ERROR = "SEARCH_PRODUCT_ERROR"
const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS"
const SEARCH_PRODUCT_INPUT_TEXT = "SEARCH_PRODUCT_SEARCH_PRODUCT_INPUT_TEXT"

export {SEARCH_PRODUCT_ERROR,SEARCH_PRODUCT_LOADING,SEARCH_PRODUCT_SUCCESS,SEARCH_PRODUCT_INPUT_TEXT}
