const USER_ADD_TO_CART_INCREMENT = "USER_ADD_TO_CART_INCREMENT";
const USER_ADD_TO_CART_DECREMENT = "USER_ADD_TO_CART_DECREMENT";
const USER_ADD_TO_CART = "USER_ADD_TO_CART";
const USER_ADD_TO_CART_LOADING = "USER_ADD_TO_CART_LOADING"
const USER_ADD_TO_CART_ERROR = "USER_ADD_TO_CART_ERROR"

export {USER_ADD_TO_CART_DECREMENT,USER_ADD_TO_CART_INCREMENT,USER_ADD_TO_CART,USER_ADD_TO_CART_ERROR,USER_ADD_TO_CART_LOADING}