const USER_ADD_TO_CART_INCREMENT = "USER_ADD_TO_CART_INCREMENT";
const USER_ADD_TO_CART_DECREMENT = "USER_ADD_TO_CART_DECREMENT";
const USER_ADD_TO_CART = "USER_ADD_TO_CART";

export {USER_ADD_TO_CART_DECREMENT,USER_ADD_TO_CART_INCREMENT,USER_ADD_TO_CART}